/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as RutasRouteImport } from './routes/rutas'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EncuestaRouteImport } from './routes/encuesta'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasIdRouteImport } from './routes/alertas.$id'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const RutasRoute = RutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EncuestaRoute = EncuestaRouteImport.update({
  id: '/encuesta',
  path: '/encuesta',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasIdRoute = AlertasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlertasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRouteWithChildren
  '/encuesta': typeof EncuestaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/reportar': typeof ReportarRoute
  '/rutas': typeof RutasRoute
  '/splash': typeof SplashRoute
  '/alertas/$id': typeof AlertasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRouteWithChildren
  '/encuesta': typeof EncuestaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/reportar': typeof ReportarRoute
  '/rutas': typeof RutasRoute
  '/splash': typeof SplashRoute
  '/alertas/$id': typeof AlertasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRouteWithChildren
  '/encuesta': typeof EncuestaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/reportar': typeof ReportarRoute
  '/rutas': typeof RutasRoute
  '/splash': typeof SplashRoute
  '/alertas/$id': typeof AlertasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/encuesta'
    | '/onboarding'
    | '/perfil'
    | '/reportar'
    | '/rutas'
    | '/splash'
    | '/alertas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/encuesta'
    | '/onboarding'
    | '/perfil'
    | '/reportar'
    | '/rutas'
    | '/splash'
    | '/alertas/$id'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/encuesta'
    | '/onboarding'
    | '/perfil'
    | '/reportar'
    | '/rutas'
    | '/splash'
    | '/alertas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRouteWithChildren
  EncuestaRoute: typeof EncuestaRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  ReportarRoute: typeof ReportarRoute
  RutasRoute: typeof RutasRoute
  SplashRoute: typeof SplashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rutas': {
      id: '/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof RutasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encuesta': {
      id: '/encuesta'
      path: '/encuesta'
      fullPath: '/encuesta'
      preLoaderRoute: typeof EncuestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas/$id': {
      id: '/alertas/$id'
      path: '/$id'
      fullPath: '/alertas/$id'
      preLoaderRoute: typeof AlertasIdRouteImport
      parentRoute: typeof AlertasRoute
    }
  }
}

interface AlertasRouteChildren {
  AlertasIdRoute: typeof AlertasIdRoute
}

const AlertasRouteChildren: AlertasRouteChildren = {
  AlertasIdRoute: AlertasIdRoute,
}

const AlertasRouteWithChildren =
  AlertasRoute._addFileChildren(AlertasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRouteWithChildren,
  EncuestaRoute: EncuestaRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  ReportarRoute: ReportarRoute,
  RutasRoute: RutasRoute,
  SplashRoute: SplashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
