/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as ComerciosRouteImport } from './routes/comercios'
import { Route as IndexRouteImport } from './routes/index'

const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerciosRoute = ComerciosRouteImport.update({
  id: '/comercios',
  path: '/comercios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comercios': typeof ComerciosRoute
  '/inteligencia': typeof InteligenciaRoute
  '/perfil': typeof PerfilRoute
  '/reportar': typeof ReportarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comercios': typeof ComerciosRoute
  '/inteligencia': typeof InteligenciaRoute
  '/perfil': typeof PerfilRoute
  '/reportar': typeof ReportarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comercios': typeof ComerciosRoute
  '/inteligencia': typeof InteligenciaRoute
  '/perfil': typeof PerfilRoute
  '/reportar': typeof ReportarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comercios' | '/inteligencia' | '/perfil' | '/reportar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comercios' | '/inteligencia' | '/perfil' | '/reportar'
  id:
    | '__root__'
    | '/'
    | '/comercios'
    | '/inteligencia'
    | '/perfil'
    | '/reportar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComerciosRoute: typeof ComerciosRoute
  InteligenciaRoute: typeof InteligenciaRoute
  PerfilRoute: typeof PerfilRoute
  ReportarRoute: typeof ReportarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercios': {
      id: '/comercios'
      path: '/comercios'
      fullPath: '/comercios'
      preLoaderRoute: typeof ComerciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComerciosRoute: ComerciosRoute,
  InteligenciaRoute: InteligenciaRoute,
  PerfilRoute: PerfilRoute,
  ReportarRoute: ReportarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
